# Generated by Django 2.0.7 on 2019-04-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_async', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='failed_on',
            field=models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('STARTED', 'Started'), ('EXPORTING', 'Exporting'), ('ENCODING', 'Encoding'), ('SAVING', 'Saving'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started'), ('EXPORTING', 'Exporting'), ('ENCODING', 'Encoding'), ('SAVING', 'Saving'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='WAITING', max_length=32),
        ),
    ]
